### ISSUE TITLE
ION_EXCHANGE_SEPARATOR gone after placing in few seconds

### ISSUE THREAD

**Issue by raihanADI** [Seggan/SlimefunWarfare#37] opened 2021-09-08 14:15 UTC
version i use is
SlimefunWarfare - DEV 63 (git 7da32).jar
with Slimefun4 - DEV 966 (git ab8f2).jar
after placing a ION_EXCHANGE_SEPARATOR, its always gone after few seconds. maybe in 2-4 second

**Comment by raihanADI** [comment] 2021-09-08 14:17
and i get this too

[10:23:49] [Server thread/INFO]: [SlimefunWarfare] Enabling SlimefunWarfare vDEV - 63 (git 7da32599)
[10:23:49] [Server thread/ERROR]: [SlimefunWarfare] Item "MODULE_MANIPULATOR" from SlimefunWarfare vDEV - 63 (git 7da32599) has caused an Error!
[10:23:49] [Server thread/ERROR]: [SlimefunWarfare] You can report it here: https://github.com/Seggan/SlimefunWarfare/issues
[10:23:49] [Server thread/ERROR]: [SlimefunWarfare] Registering ModuleManipulator - 'MODULE_MANIPULATOR' (SlimefunWarfare vDEV - 63 (git 7da32599)) has failed!
io.github.thebusybiscuit.slimefun4.api.exceptions.IdConflictException: Two items have conflicting ids: ModuleManipulator - 'MODULE_MANIPULATOR' (SlimefunWarfare vDEV - 63 (git 7da32599)) and ModuleManipulator - 'MODULE_MANIPULATOR' (SlimefunWarfare vDEV - 63 (git 7da32599))
	at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.checkForConflicts(SlimefunItem.java:592) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.register(SlimefunItem.java:421) ~[?:?]
	at io.github.seggan.slimefunwarfare.Setup.setupSuits(Setup.java:417) ~[?:?]
	at io.github.seggan.slimefunwarfare.SlimefunWarfare.enable(SlimefunWarfare.java:76) ~[?:?]
	at io.github.seggan.slimefunwarfare.infinitylib.core.AbstractAddon.onEnable(AbstractAddon.java:194) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-786]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Seggan** [comment] 2021-09-08 16:57
2nd error is duplicate of #36

**Comment by Seggan** [comment] 2021-09-08 16:57
> version i use is
> SlimefunWarfare - DEV 63 (git 7da32).jar
> with Slimefun4 - DEV 966 (git ab8f2).jar
> after placing a ION_EXCHANGE_SEPARATOR, its always gone after few seconds. maybe in 2-4 second

show me the error report generated in `/plugins/Slimefun/error-reports`

**Comment by raihanADI** [comment] 2021-09-09 00:31
Error Generated: 2021-09-08-13-58

Java Environment:
  Operating System: Linux
  Java Version: 16.0.2

Server Software: Paper
  Build: git-Paper-786 (MC: 1.16.5)
  Minecraft v1.16.5-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vDEV - 966 (git ab8f20f0)
  Caused by: SlimefunWarfare vDEV - 63 (git 7da32599)

Installed Addons (15)
  + EcoPower DEV - 5 (git 5c1ecd68)
  + ExtraGear DEV - 13 (git c62047e2)
  + SFCalc DEV - 34 (git 60f3c45d)
  + AlchimiaVitae DEV - 11 (git 1045879d)
  + SlimefunLuckyBlocks DEV - 36 (git 60f0c8dc)
  + ExoticGarden DEV - 77 (git a2c4b6d3)
  + LiteXpansion DEV - 155 (git 574d551a)
  + SoulJars DEV - 23 (git b8358a1f)
  + ExtraTools DEV - 29 (git 83f6db7f)
  + FluffyMachines DEV - 90 (git b36089e8)
  + InfinityExpansion DEV - 122 (git 74e896f0)
  + SlimefunWarfare DEV - 63 (git 7da32599)
  + DynaTech DEV - 133 (git f1901252)
  + CMILib 1.0.3.7
  + CMI 9.0.2.5

Installed Plugins (68):
  + PlaceholderAPI 2.10.10
  + PublicBin 1.1.0
  + NametagEdit 4.4.10
  + AntiWorldFly 2.4.1
  + SkinsRestorer 14.1.3
  + Quests 3.8
  + nTrivia 1.2.1
  + TabCompleteFilter 1.0.8
  + ViaVersion 4.0.1
  + EpicPluginLib 2.0
  + NBTAPI 2.8.0
  + LuckPerms 5.3.47
  + ClearLag 3.2.2
  + Votifier 2.7.3
  + ProtocolLib 4.7.0
  + ImageOnMap 4.1.2
  + Vault 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
  + DailyRewards 1.0.9
  + CrazyCrates 1.10.1-RELEASE
  + Scoreboard-revision R4 1.1 RELEASE
  + VoteParty 2.24
  + BungeeGuard 1.2-SNAPSHOT
  + PlayerVaults 4.2.2
  + PlayMoreSounds 4.0.4
  + ShopGUIPlus 1.62.2
  + WorldEdit 7.2.5+57d5ac9
  + ClearLagTimer Build 30b
  + Multiverse-Core 4.3.0-b846
  + DiscordSRV 1.23.0
  + DiscordSRVUtils 1.1.9
  + DeluxeMenus 1.13.3-Release
  + WorldGuard 7.0.5+3827266
  + BetterTeams 4.0.4
  + AuctionHouse 2.2
  + antiRedstoneClock 1.4.1
  + Images 2.2.3
  + Slimefun DEV - 966 (git ab8f20f0)
  + ReportSystem 1.0.4
  + EcoPower DEV - 5 (git 5c1ecd68)
  + CoreProtect 20.1
  + CrazyEnchantments 1.8-Dev-Build-v9-RELEASE
  + ExtraGear DEV - 13 (git c62047e2)
  + PlayerWarps 6.9.2
  + SFCalc DEV - 34 (git 60f3c45d)
  + RedProtect 7.7.2
  + WorldBorder 2.1.2
  + Randomtp 2.19.3-RELEASE
  + Citizens 2.0.28-SNAPSHOT (build 2325)
  + AlchimiaVitae DEV - 11 (git 1045879d)
  + SlimefunLuckyBlocks DEV - 36 (git 60f0c8dc)
  + ExoticGarden DEV - 77 (git a2c4b6d3)
  + LiteXpansion DEV - 155 (git 574d551a)
  + SoulJars DEV - 23 (git b8358a1f)
  + ExtraTools DEV - 29 (git 83f6db7f)
  + AureliumSkills Beta 1.2.0
  + BlockRegen 3.5.8
  + Matrix 6.3.0
  + AdvancedDiscordLogger 1.1-BETA
  + FluffyMachines DEV - 90 (git b36089e8)
  + BattlePass 3.49
  + SmoothTimber 1.16.5
  + InfinityExpansion DEV - 122 (git 74e896f0)
  + SlimefunWarfare DEV - 63 (git 7da32599)
  + DynaTech DEV - 133 (git f1901252)
  + InteractiveChat 4.0.0.13
  + InteractiveChatDiscordSrvAddon 4.0.0.12
  + CMILib 1.0.3.7
  + CMI 9.0.2.5

Block Info:
  World: world
  X: 704
  Y: 75
  Z: -81
  Material: SEA_LANTERN
  Block Data: org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData
  State: org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockState

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: ION_EXCHANGE_SEPARATOR
  Inventory: true
  Data: {"energy-charge":"256","id":"ION_EXCHANGE_SEPARATOR"}

Stacktrace:

java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.hasItemMeta()" because "item" is null
	at io.github.seggan.slimefunwarfare.infinitylib.common.StackUtils.getId(StackUtils.java:29)
	at io.github.seggan.slimefunwarfare.machines.IonExchangeSeparator.process(IonExchangeSeparator.java:90)
	at io.github.seggan.slimefunwarfare.infinitylib.machines.AbstractMachineBlock.tick(AbstractMachineBlock.java:37)
	at io.github.seggan.slimefunwarfare.infinitylib.machines.TickingMenuBlock$1.tick(TickingMenuBlock.java:34)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:176)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:146)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:115)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Closed** 2021-09-09 17:13 UTC
