### ISSUE TITLE
Getting Error in every second

### ISSUE THREAD

**Issue by WongIong** [Seggan/SlimefunWarfare#33] opened 2021-08-24 14:34 UTC
[22:33:22 ERROR]: Could not pass event EntityDamageByEntityEvent to SlimefunWarf
are vDEV - 57 (git a461573d)
java.lang.IllegalStateException: Cannot invoke static method, Slimefun instance
is null.
        at io.github.thebusybiscuit.slimefun4.implementation.SlimefunPlugin.vali
dateInstance(SlimefunPlugin.java:705) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.implementation.SlimefunPlugin.getI
temDataService(SlimefunPlugin.java:786) ~[?:?]
        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem.getByItem
(SlimefunItem.java:1137) ~[?:?]
        at io.github.seggan.slimefunwarfare.listeners.HitListener.onEnergyBladeH
it(HitListener.java:29) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventEx
ecutor842.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69
) ~[patched_1.16.5.jar:git-Paper-783]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:8
0) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:624) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(Cra
ftEventFactory.java:257) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDam
ageEvent(CraftEventFactory.java:1091) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityD
amageEvent(CraftEventFactory.java:978) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityD
amageEvent(CraftEventFactory.java:934) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingE
ntityDamageEvent(CraftEventFactory.java:1123) ~[patched_1.16.5.jar:git-Paper-783
]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving
.java:1932) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.
java:1260) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonste
r.java:74) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityEnderman.damageEntity(EntityEnder
man.java:389) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:119
6) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2
022) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.jav
a:2413) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUse
Entity.java:55) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUse
Entity.java:12) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMain
Thread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1
.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTas
kHandler.java:136) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(
SourceFile:23) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTas
kHandler.java:109) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java
:1266) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftSe
rver.java:1259) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTask
Handler.java:119) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftS
erver.java:1220) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:
1134) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftSer
ver.java:291) ~[patched_1.16.5.jar:git-Paper-783]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]

**Comment by Seggan** [comment] 2021-08-24 17:11
Show me your **full** error log

**Comment by WongIong** [comment] 2021-09-08 14:50
Its now gone already.
but i got this at startup

[04:03:57] [Server thread/INFO]: [SlimefunWarfare] Enabling SlimefunWarfare vDEV - 63 (git 7da32599)
[04:03:58] [Server thread/ERROR]: [SlimefunWarfare] Item "MODULE_MANIPULATOR" from SlimefunWarfare vDEV - 63 (git 7da32599) has caused an Error!
[04:03:58] [Server thread/ERROR]: [SlimefunWarfare] You can report it here: https://github.com/Seggan/SlimefunWarfare/issues
[04:03:58] [Server thread/ERROR]: [SlimefunWarfare] Registering ModuleManipulator - 'MODULE_MANIPULATOR' (SlimefunWarfare vDEV - 63 (git 7da32599)) has failed!
io.github.thebusybiscuit.slimefun4.api.exceptions.IdConflictException: Two items have conflicting ids: ModuleManipulator - 'MODULE_MANIPULATOR' (SlimefunWarfare vDEV - 63 (git 7da32599)) and ModuleManipulator - 'MODULE_MANIPULATOR' (SlimefunWarfare vDEV - 63 (git 7da32599))
	at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.checkForConflicts(SlimefunItem.java:592) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.register(SlimefunItem.java:421) ~[?:?]
	at io.github.seggan.slimefunwarfare.Setup.setupSuits(Setup.java:417) ~[?:?]
	at io.github.seggan.slimefunwarfare.SlimefunWarfare.enable(SlimefunWarfare.java:76) ~[?:?]
	at io.github.seggan.slimefunwarfare.infinitylib.core.AbstractAddon.onEnable(AbstractAddon.java:194) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-783]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-783]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-783]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-783]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-783]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-783]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-783]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-783]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-783]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Seggan** [comment] 2021-09-08 16:56
Duplicate of #36

**Closed by Seggan** 2021-09-08 16:56 UTC
Labels: status: waiting for more info

**Comment by WongIong** [comment] 2021-09-08 17:08
i am confused now. i have only one copy of Slimefunwarfare in plugins folder. What should i do now?

**Comment by Seggan** [comment] 2021-09-08 17:14
This has been fixed in latest

**Comment by WongIong** [comment] 2021-09-08 17:24
Do i need to restart the server for updating?

**Comment by WongIong** [comment] 2021-09-08 17:27
ok thank u
